FROM python:3.12-alpine

WORKDIR /apps

COPY requirements.txt .
#RUN apt update -y
RUN pip install --no-cache-dir -r requirements.txt

COPY validador.py .

#CMD ["python", "validador.py"]
ENTRYPOINT python -u validador.py